language: python

os:
  - linux

python:
  - 3.6
  - 3.6-dev

cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


install:
  - pip install virtualenv --upgrade
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - py.test --cov=gdax --cov-report=term --cov-append tests

after_success:
  - codecov

notifications:
  email: false
